%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
M3
(Header end.)
G21 (All units in mm)

(Start cutting path id: rect1922)
(Change tool to Default tool)

G00 Z5.000000
G00 X0.500787 Y378.453528

G01 Z-0.125000 F100.0(Penetrate)
G01 X378.453550 Y378.453528 Z-0.125000 F400.000000
G01 X378.453550 Y0.500788 Z-0.125000
G01 X0.500787 Y0.500788 Z-0.125000
G01 X0.500787 Y378.453528 Z-0.125000
G00 Z5.000000

(End cutting path id: rect1922)


(Footer)
M5
G00 X0.0000 Y0.0000
M2
(Using default footer. To add your own footer create file "footer" in the output dir.)
(end)
%